// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
    int n = Integer.parseInt(args[0]);
	int countsGreater = 0;
	int countsLesser = 0;
	double r;
	for (int i = 0; i < n; i++) {
		r = Math.random();
		if (r > 0.5) {
			countsGreater++;
		} else {
			countsLesser++;
		}
	}
		System.out.println("> 0.5: " + countsGreater + "times");
		System.out.println("<= 0.5: " + countsLesser + "times");
		if (countsLesser > 0) {
			double ratio = (double) countsGreater / countsLesser;
			System.out.println("Ratio > 0.5 to <= 0.5: " + ratio);
		}

	
  }
}